version: "3.8"

services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      MONGO_URL: mongodb+srv://rasagnak6_db_user:test123@microservicesdata.v9zjclz.mongodb.net/

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8002:8000"
    environment:
      MONGO_URL: mongodb+srv://rasagnak6_db_user:test123@microservicesdata.v9zjclz.mongodb.net/

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    ports:
      - "8003:8000"
    environment:
      MONGO_URL: mongodb+srv://rasagnak6_db_user:test123@microservicesdata.v9zjclz.mongodb.net/

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8004:8000"
    environment:
      MONGO_URL: mongodb+srv://rasagnak6_db_user:test123@microservicesdata.v9zjclz.mongodb.net/

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8005:8000"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8000:8000"

  load-generator:
    build:
      context: .
      dockerfile: load-generator/Dockerfile
    ports:
      - "8006:8000"

  phase3_aiops:
    build:
      context: .
      dockerfile: phase3_aiops/Dockerfile
    container_name: phase3_aiops
    ports:
      - "8010:8010"
    volumes:
      - ./phase3_aiops:/app/phase3_aiops
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prometheus
      - order-service
      - payment-service
      - inventory-service
      - user-service
      - notification-service
      - api-gateway
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - order-service
      - payment-service
      - inventory-service
      - user-service
      - notification-service
      - api-gateway

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana   
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

volumes:
  grafana-storage: