apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-healing-app
  template:
    metadata:
      labels:
        app: self-healing-app
    spec:
      containers:
        - name: app
          image: self-healing-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8000